name: Print status of Codecov patch workflow

on:
  workflow_run:
    workflows: ['codecov/patch']
    types:
      - completed

jobs:
  print-status:
    runs-on: ubuntu-latest

    steps:
    - name: Print status
      run: |
        echo "Workflow run ID: ${{ github.event.workflow_run.id }}"
        echo "Workflow run conclusion: ${{ github.event.workflow_run.conclusion }}"
        echo "Workflow run status: ${{ github.event.workflow_run.status }}"