name: CI

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run tests with coverage
      run: go test -v -coverprofile=coverage.out ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: coverage.out
        flags: unittests
        fail_ci_if_error: true
        codecov_yml_path: codecov.yml
        token: ${{ secrets.CODECOV_TOKEN }}

  enforce-coverage:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Enforce code coverage
      timeout-minutes: 60
      id: codecov-status
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        echo "Polling Codecov status..."
        while true; do
          codecov_check_run=$(gh api repos/${{ github.repository }}/commits/${{ github.event.pull_request.head.sha }}/check-runs | jq -r '.check_runs[] | select(.name == "codecov/patch")')
          status=$(echo "$codecov_check_run" | jq -r '.status')
          if [[ "$status" == "completed" ]]; then
            conclusion=$(echo "$codecov_check_run" | jq -r '.conclusion')

            if [[ "$conclusion" == "success" ]]; then
              exit 0
            fi

            exit 1
          fi
          echo "Waiting for Codecov status..."
          sleep 10
        done

